config/routes.rb
ToDont::Application.routes.draw do

  devise_for :users

  resources :lists do
    collection { post :sort }
      resources :tasks do
        resources :reminders
      end
  end

  get "/lists/:list_id/tasks/:id/send_sms" => "tasks#send_sms", :as => "send_sms_tasks"

  get "/lists/:id/deleted" => "lists#deleted_tasks", :as => "deleted_tasks"

  root :to => "users#sign_in"

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :title
  has_many :tasks
  belongs_to :user
end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
  attr_accessible :task_id, :time, :date
  belongs_to :task
  after_create :send_sms


  def send_sms
    @task = Reminder.last.task
    current_user = Reminder.last.task.list.user
    account_sid = "ACe3f08f26920946de8394b08ad903b161"
    auth_token = "c86b4df4b436dbf4f4b202ef11196d46"
    client = Twilio::REST::Client.new account_sid, auth_token

    from = "+18473803186" # Your Twilio number
    contact_info = {
    current_user.phone_number => task.description,
    }
    contact_info.each do |key, value|
      client.account.sms.messages.create(
        :from => from,
        :to => key,
        :body => value
      )
      puts "Sent message to #{value}"
    end
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :description, :list_id, :date, :date_american, :order, :alive, :order, :id
  belongs_to :list
  has_many :reminders

  scope :active, where(:alive => true)
  scope :inactive, where(:alive => false)

  after_initialize :set_date!
  after_create :assign_order

  def deactivate!
    update_attributes(:alive => false)
  end

  def date_american=(date)
    self.date = Date.strptime(date, '%m-%d-%Y')
  end

  def date_american
    self.date.strftime('%m-%d-%Y')
  end

  private
  def set_date!
    self.date ||= Date.today
  end

  def assign_order
    self.order = self.id
    self.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :phone_number
  # attr_accessible :title, :body
  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def formatted_date(string)
    Date.parse(string.gsub(/(.+)-(\d{4})/, '\2-\1'))
  end

  helper_method :formatted_date

  def date_in_english(task)
    case task.date - Date.today
    when 0
      "Today"
    when 1
      "Tomorrow"
    when 2
      "Two Days"
    when 3
      "Three Days"
    else
      task.date.strftime("%B %d")
    end
  end

  helper_method :date_in_english
end



  # def date_in_english(task)
  #   if task.date = "2012-11-18"
  #     task.date = "Today"
  #   end
  # end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  respond_to :html, :json
  before_filter :authenticate_user!

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params[:list])
    @list.user_id = current_user.id
    redirect_to lists_path if @list.save
  end

  def show
    @list = List.find(params[:id])
    @task = @list.tasks.build
    @tasks = @list.tasks.active.sort_by &:order
    @reminder = Reminder.new
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update_attributes(params[:list])
    respond_with @list
  end

  def deleted_tasks
    @list = List.find(params[:id])
    @tasks = @list.tasks.inactive
  end

  def sort
    params[:row_task].each_with_index do |id, index|
      Task.update_all({order: index+1}, {id: id})
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :authenticate_user!, :only => :token

  def new
      super
    end


  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "You have signed up successfully. If enabled, a confirmation was sent to your e-mail."
      redirect_to root_url
    else
      render :action => :new
    end
  end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @task = Task.find(params[:task_id])
    @reminder = Reminder.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @list = List.find(params[:list_id])
    @task = Task.find(params[:task_id])
    @reminder = Reminder.new(params[:reminder])
    @reminder.task_id = @task.id
    redirect_to lists_path if @reminder.save
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  respond_to :html, :json

  def index
    redirect_to list_path(params[:list_id])
  end

  def new
    @list = List.find(params[:list_id])
    @task = Task.new
  end

  def create
    task_params = params[:task]

    @list = List.find(params[:list_id])
    @task = @list.tasks.new(task_params)

    if @task.save
      respond_to do |format|
        format.js
      end
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def destroy
    @list = List.find(params[:list_id])
    @tasks = @list.tasks.active

    @task = Task.find(params[:id])

    @task.deactivate!

    respond_to do |format|
      format.js { render 'delete.js.erb' }
    end
  end

  def edit
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
  end

  def update
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
    @task.update_attributes(params[:task])
    respond_with @list
  end

  def send_sms
    @task = Task.find(params[:id])
    RemindersWorker.perform_async(@task)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def sign_in
  	redirect_to lists_path
  end

  def password_match?
    self.errors[:password] << 'must be provided' if password.blank?
    self.errors[:password] << 'and confirmation do not match' if password != password_confirmation
    password == password_confirmation and !password.blank?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_error_messaging.html.erb
<div id="error_container">
    <div class="twelve columns">
      <% flash.keys.each do |key| %>
        <div class="<%= key %>"><%= flash[key] %></div>
      <% end %>
    </div><!-- //.twelve.columns -->
</div><!-- //.container -->

app/views/application/_navigation.html.erb
    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">

          <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
          </a>

          <!-- Be sure to leave the brand out there if you want it shown -->
          <a class="brand" href="/lists">TewDew</a>

          <!-- Everything you want hidden at 940px or less, place within here -->
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li><a href="#">link</a></li>
              <li><a href="#">Link</a></li>
            </ul>
            <ul class="nav pull-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
                </ul>
              </li>
            </ul>
          </div>

        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDont</title>
      <%= stylesheet_link_tag    "application", :media => "all" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
  </head>
    <body>
      <%= render 'navigation'%>
      <div class = "container">
      <%= render 'error_messaging'%>
          <%= yield %>
        </div>
    </body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_area :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/lists/_header.html.erb
<header>	
  <h1>
    <%= best_in_place @list, :title %>
  </h1>

 	 	
  <thead>
 	 	
    Tasks
 	 	
  </thead> 
 	 	
   <div class = "new_task_form">
      <%= render 'tasks/form' %>
    </div>	
</header

app/views/lists/_list.html.erb
<table class="table table-hover">
  <tbody class="list_content" data-update-url="<%= sort_lists_url%> ">
    <% @tasks.each do |task| %>
      <%= render :partial => 'tasks/row', :locals => {:task => task, :list => @list, :reminder => @reminder } %>
    <% end %>
  </tbody>
</table>

app/views/lists/_modal.html.erb
<!-- Modal -->
<div id="myModal" class="modal hide fade"tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    <%= render 'reminders/form'%>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary" data-dismiss="modal" aria-hidden="true"></button>
  </div>
</div>

app/views/lists/deleted_tasks.html.erb
<h1>Deleted Tasks</h1>
<div class = "form_container">
  <div class = "form">
    <%= render 'tasks/form' %>
  </div>
  <div class = "completed_tasks">
    <%= button_to 'Delete All', {:action => 'deleted_tasks'}, :method => :get, :class => "btn btn-primary"  %>
  </div>
</div>




    <%= render 'list', :post => @tasks%>



<%= link_to 'New Task', new_list_task_path(@list), :method => :get %>
<br>
<%= link_to 'Lists', lists_path %>

app/views/lists/index.html.erb
<h1>Your ToDo Lists</h1>

<% @lists.each do |list| %>
<table>
<tr>
  <th><%= list.title %></th>
  <th><%= link_to 'See', list_path(list.id) %>
  <th><%= link_to 'Add', new_list_task_path(list.id) %>
  <th></th>
<% end %>
</tr>
</table>
<br>
<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>Create a New List</h1>

<%= render 'form' %>

app/views/lists/show.html.erb
<div id = "list-title" class="span12">
  <h1><%= best_in_place @list, :title %></h1>
</div>

  <div id = "sub-nav" class="row span12">
    <%= render 'tasks/form' %>
      <ul class="nav nav-pills">
        <li class="active"><a href="#">Today</a></li>
        <li><a href="#">Tomorrow</a></li>
        <li><a href="#">This Week</a></li>
        <li><a href="#">All</a></li>
      </ul>
    <div class = "completed-tasks">
      <%= button_to 'Completed Tasks', {:action => 'deleted_tasks'}, :method => :get, :class => "btn btn-primary"  %>
    </div>
  </div>

  <%= render 'list'%>
  <%= link_to 'New Task', new_list_task_path(@list), :method => :get %>
  <br>

  <%= link_to 'Lists', lists_path %>

  <br><br>

  <br><br>

  <%= render 'modal'%>

app/views/reminders/_form.html.erb
<%= form_for([@list, @task = Task.find(params[:id]), @reminder], :remote => true ) do |f| %>
   <% if @task.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

       <ul>
       <% @task.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
       </ul>
     </div>
   <% end %>
   <div class = "fields">
     <%= f.label :date %>
     <%= f.date_select :date, :discard_year => true %>
     <%= f.label :time %>
     <%= f.time_select :time, :discard_year => true %>

     <%= f.submit "create"%>
    </div>
<% end %>

app/views/reminders/_modal.html.erb
<!-- Button to trigger modal -->
<a href="#myModal" role="button" data-backdrop="static" data-keyboard="false" class="btn" data-toggle="modal">Launch demo modal</a>

<!-- Modal -->
<div id="myModal" class="modal hide fade"tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    <p><%= render 'reminders/form' %></p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true"></button>
    <button class="btn btn-primary">Save changes</button>
  </div>
</div>

app/views/reminders/index.html.erb
CHeck Check CHeck

app/views/reminders/new.js.erb
$('#myModal').modal('show');

app/views/tasks/_form.html.erb
<%= form_for([@list,@task ], :remote => true ) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "fields">
    <%= f.text_field :description, :placeholder => "New Task" %>
    <%= f.text_field :date_american, :class => 'datepicker' %>
    <button type="submit" class="btn" style = "margin-bottom: 10px; margin-left: 4px;"><i class="icon-plus-sign"></i></button>
  </div>

<% end %>

app/views/tasks/_modal.html.erb
<!-- Button to trigger modal -->
<a href="#myModal" role="button" data-backdrop="static" data-keyboard="false" class="btn" data-toggle="modal">Launch demo modal</a>

<!-- Modal -->
<div id="myModal" class="modal hide fade"tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    <p><%= render 'reminders/form', :locals => { :reminder => @reminder } %></p>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary" data-dismiss="modal" aria-hidden="true"></button>
  </div>
</div>

app/views/tasks/_row.html.erb
<tr id="<%= dom_id(task, :row) %>" class="task">
  <td>
    <%= best_in_place task, :description, :path => list_task_path(@list, task), :method => "put" %>
  </td>
  <td>
    <span class="date">
      <%= date_in_english(task) %>
    </span>
  </td>
  <td>
      <span class="text_link">
   <%= link_to "text", new_list_task_reminder_path(@list, task), :remote => true %>
      </span>
  </td>
  <td style="text-align:right;">
    <%= link_to '', list_task_path(@list, task), :method => "delete", :class => 'icon-ok', :remote => true %>
  </td>
</tr>

app/views/tasks/create.js.erb
$('.table').append("<%= j(render 'tasks/row', :task => @task, :list => @list) %>");
$('#task_description').val('');

app/views/tasks/delete.js.erb
$('#row_<%=dom_id(@task)%>').remove();
// $(console.log("<%= @list.tasks.count %>"))


// $('.table').append("<%= j(render :partial => 'row', :locals => { :task => @task }) %>")

app/views/tasks/edit.html.erb
<h1><%= @task.description %></h1>

<%= form_for [@list, @task] do |f| %>
  <%= f.label :edit %>
	<%= f.text_field :description %>
<%= f.submit 'Submit' %>
<% end %>

app/views/tasks/index.html.erb
<h1>Here are your tasks</h2>

<% @tasks.each do |task| %>
<table>
<tr>
<th><%= task.description %></th>
</tr>
</table>
<% end %>

app/views/tasks/new.html.erb
<h1>Create a New Task</h1>

<%= render 'form' %>


<% @title = "check it, Yo" %>
<% @title = @title.chars.to_a %>
<% @colors = ["#097054", "#FFDE00", "#6599FF", "#FF9900", "#587058", "#587498", "#E86850", "#99CCFF", "#FF9900", "#00CC00", "#993366"] %>
<%@color_title = ""%>
<h1><% @title.each do |letter| %>
  <span style = "color: <%= @colors[0]%>;">
  <%=letter%>
  <% @color_title << "<span style = 'color: " + @colors[0] + "'>" + letter + "</span>" %>
  <% @colors = @colors << @colors.shift %>
<% end %></h1>
  
  <%= @color_title %>